# Copyright CETC Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  messagehub:
    container_name: messagehub
    image: messagehub
    tty: true
    working_dir: /usr/local/bin
    environment:
      - LOCAL_URL=http://172.16.0.53:8000
      - SERVER_URL=http://172.16.2.16:8081
      - REGISTER_URL=http://172.16.0.250:6000
    command: messagehub
    ports:
      - 8000:8000