# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  distServer:
    container_name: distServer
    image: distserver
    tty: true
    working_dir: /usr/local/bin
    command: distServer
    ports:
      - 8080:8080
      - 6000:6000

  cryptoServer:
    container_name: cryptoServer
    image: normalcrypto
    tty: true
    working_dir: /usr/local/bin
    command: normalCrypto
    depends_on:
      - distServer
    ports:
      - 8081:8081

  messagehub:
    container_name: messagehub
    image: messagehub
    tty: true
    working_dir: /usr/local/bin
    environment:
      - LOCAL_URL=http://172.16.0.250:8000
      - SERVER_URL=http://172.16.2.250:8081
      - REGISTER_URL=http://172.16.0.250:6000
    command: messagehub
    depends_on:
      - distServer
      - cryptoServer
    ports:
      - 8000:8000
