# Copyright Greg Haskins All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
FROM ubuntu:16.04
MAINTAINER xl-cetc

COPY payload/distServer /usr/local/bin
EXPOSE 8080
EXPOSE 6000
CMD ["distServer"]
